#!/bin/sh

cd command_line_migration
./users_command_line_migration.php
./personal_agendas_command_line_migration.php
./system_settings_command_line_migration.php
./classes_command_line_migration.php
./courses_command_line_migration.php
./meta_data_command_line_migration.php
./groups_command_line_migration.php
./announcements_command_line_migration.php
./calendar_events_command_line_migration.php
./documents_command_line_migration.php
./links_command_line_migration.php
./dropboxes_command_line_migration.php
./forums_command_line_migration.php
./learning_paths_command_line_migration.php
./quizzes_command_line_migration.php
./student_publications_command_linem_igration.php
./surveys_commandl_ine_migration.php
./scorms_command_line_migration.php
./assignments_command_line_migration.php
./user_infos_command_line_migration.php
./trackers_command_line_migration.php
cd ..