<?php
namespace common\extensions\external_repository_manager\implementation\photobucket;

use common\extensions\external_repository_manager\DefaultExternalRepositoryGalleryObjectTableDataProvider;

class PhotobucketExternalRepositoryGalleryTableDataProvider extends DefaultExternalRepositoryGalleryObjectTableDataProvider
{
}
?>