<?php
namespace common\extensions\external_repository_manager\implementation\picasa;

use common\extensions\external_repository_manager\DefaultExternalRepositoryGalleryObjectTableDataProvider;

class PicasaExternalRepositoryGalleryTableDataProvider extends DefaultExternalRepositoryGalleryObjectTableDataProvider
{
}
?>