<?php
namespace common\extensions\external_repository_manager\implementation\picasa;
use common\extensions\external_repository_manager\DefaultExternalRepositoryObjectTableDataProvider;
class PicasaExternalRepositoryTableDataProvider extends DefaultExternalRepositoryObjectTableDataProvider
{
}
?>