<?php
namespace common\extensions\external_repository_manager\implementation\youtube;
use common\extensions\external_repository_manager\DefaultExternalRepositoryObjectTableDataProvider;
class YoutubeExternalRepositoryTableDataProvider extends DefaultExternalRepositoryObjectTableDataProvider
{
}
?>