<?php
namespace common\extensions\external_repository_manager\implementation\hq23;

use common\extensions\external_repository_manager\DefaultExternalRepositoryGalleryObjectTableDataProvider;

class Hq23ExternalRepositoryGalleryTableDataProvider extends DefaultExternalRepositoryGalleryObjectTableDataProvider
{
}
?>