<?php
namespace common\extensions\external_repository_manager\implementation\hq23;
use common\extensions\external_repository_manager\DefaultExternalRepositoryObjectTableDataProvider;
class Hq23ExternalRepositoryTableDataProvider extends DefaultExternalRepositoryObjectTableDataProvider
{
}
?>